//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation.BloodDonationEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorId { get; set; }
        public int BloodId { get; set; }
        public int UserId { get; set; }
    
        public virtual Blood Blood { get; set; }
        public virtual User User { get; set; }
    }
}
