//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation.BloodDonationEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int HospitalId { get; set; }
        public string Name { get; set; }
        public string ContectNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    }
}
